name: Run IMD Script Daily

on:
  schedule:
    - cron: '30 2 * * *'  # 8:00 AM IST (IST = UTC+5:30)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    permissions:
      contents: write  # <-- This gives permission to push changes using GITHUB_TOKEN

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install imdlib pandas xarray

      - name: Run IMD Script
        run: python "IMD_Data_Automate.py"

      - name: Commit and push new CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/*.csv || echo "No files to add"
          git diff --cached --quiet || git commit -m "Update rainfall data CSVs"
          git push
